import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:monthly_management/app_shell.dart';
import 'package:monthly_management/l10n/generated/app_localizations.dart';
import 'package:monthly_management/models/data_health_status.dart';
import 'package:monthly_management/screens/confidence_center_screen.dart';
import 'package:monthly_management/utils/data_alert_builder.dart';

import '../helpers/test_app.dart';

void main() {
  group('ConfidenceCenterScreen', () {
    testWidgets('renders sync health section with domain chips', (
      tester,
    ) async {
      await tester.pumpWidget(
        wrapWithTestApp(const ConfidenceCenterScreen(statuses: {}, alerts: [])),
      );

      // Section headers
      expect(find.text('Sync Health'), findsOneWidget);
      expect(find.text('Data Quality Alerts'), findsOneWidget);
      expect(find.text('Recommended Actions'), findsOneWidget);

      // All domain chips should appear
      expect(find.text('Settings'), findsOneWidget);
      expect(find.text('Shopping list'), findsOneWidget);
      expect(find.text('Meal plan'), findsOneWidget);
      expect(find.text('Expenses'), findsOneWidget);
      expect(find.text('Purchase history'), findsOneWidget);
      expect(find.text('Savings goals'), findsOneWidget);
      expect(find.text('Recurring expenses'), findsOneWidget);
    });

    testWidgets('shows empty state when no alerts', (tester) async {
      await tester.pumpWidget(
        wrapWithTestApp(const ConfidenceCenterScreen(statuses: {}, alerts: [])),
      );

      expect(find.text('No alerts. Everything looks good.'), findsOneWidget);
      expect(
        find.text('All systems healthy. No actions needed.'),
        findsOneWidget,
      );
    });

    testWidgets('renders alert cards with correct severity styling', (
      tester,
    ) async {
      final alerts = [
        DataAlert(
          id: 'test_critical',
          severity: AlertSeverity.critical,
          domain: SyncDomain.shopping,
          title: 'Shopping list sync failed',
          body: 'Connection error',
          recommendedAction: 'Check your connection',
          createdAt: DateTime(2026, 3, 8),
        ),
        DataAlert(
          id: 'test_warning',
          severity: AlertSeverity.warning,
          domain: SyncDomain.expenses,
          title: 'Expenses data outdated',
          body: 'Last synced 3 days ago',
          createdAt: DateTime(2026, 3, 8),
        ),
        DataAlert(
          id: 'test_info',
          severity: AlertSeverity.info,
          domain: SyncDomain.mealPlan,
          title: 'Meal plan may be outdated',
          body: 'Generated 10 days ago',
          createdAt: DateTime(2026, 3, 8),
        ),
      ];

      await tester.pumpWidget(
        wrapWithTestApp(
          ConfidenceCenterScreen(statuses: const {}, alerts: alerts),
        ),
      );

      expect(find.text('Shopping list sync failed'), findsOneWidget);
      expect(find.text('Expenses data outdated'), findsOneWidget);
      expect(find.text('Meal plan may be outdated'), findsOneWidget);
      expect(find.text('Check your connection'), findsOneWidget);
    });

    testWidgets('renders recommended actions from alerts', (tester) async {
      final alerts = [
        DataAlert(
          id: 'a1',
          severity: AlertSeverity.warning,
          title: 'Test',
          body: 'Body',
          recommendedAction: 'Do something',
          createdAt: DateTime(2026, 3, 8),
        ),
        DataAlert(
          id: 'a2',
          severity: AlertSeverity.info,
          title: 'Test2',
          body: 'Body2',
          recommendedAction: 'Do another thing',
          createdAt: DateTime(2026, 3, 8),
        ),
      ];

      await tester.pumpWidget(
        wrapWithTestApp(
          ConfidenceCenterScreen(statuses: const {}, alerts: alerts),
        ),
      );

      expect(find.text('Do something'), findsOneWidget);
      expect(find.text('Do another thing'), findsOneWidget);
    });

    testWidgets('renders alerts generated by buildAlerts in pt-PT', (
      tester,
    ) async {
      final pt = await S.delegate.load(const Locale('pt'));
      final now = DateTime.now();
      final healthy = now.subtract(const Duration(hours: 1));
      final statuses = {
        SyncDomain.settings: SyncDomainStatus(
          domain: SyncDomain.settings,
          lastLoadAt: healthy,
        ),
        SyncDomain.shopping: SyncDomainStatus(
          domain: SyncDomain.shopping,
          lastLoadAt: now.subtract(const Duration(days: 10)),
        ),
        SyncDomain.mealPlan: SyncDomainStatus(
          domain: SyncDomain.mealPlan,
          lastLoadAt: healthy,
        ),
        SyncDomain.expenses: SyncDomainStatus(
          domain: SyncDomain.expenses,
          lastLoadAt: healthy,
        ),
        SyncDomain.purchaseHistory: SyncDomainStatus(
          domain: SyncDomain.purchaseHistory,
          lastLoadAt: healthy,
        ),
        SyncDomain.savingsGoals: SyncDomainStatus(
          domain: SyncDomain.savingsGoals,
          lastLoadAt: healthy,
        ),
        SyncDomain.recurringExpenses: SyncDomainStatus(
          domain: SyncDomain.recurringExpenses,
          lastLoadAt: healthy,
        ),
      };
      final alerts = buildAlerts(statuses: statuses, now: now, l10n: pt);

      await tester.pumpWidget(
        wrapWithTestApp(
          ConfidenceCenterScreen(statuses: statuses, alerts: alerts),
          controller: AppShellController(locale: const Locale('pt')),
        ),
      );

      // Stale alert title, body and recommended action in Portuguese.
      expect(
        find.text('Os dados de Lista de compras podem estar desatualizados'),
        findsOneWidget,
      );
      expect(find.text('Última sincronização há 10 dias.'), findsOneWidget);
      expect(find.text('Abra a secção da app para atualizar.'), findsOneWidget);
    });
  });

  group('CriticalAlertBanner', () {
    testWidgets('renders nothing when count is 0', (tester) async {
      await tester.pumpWidget(
        wrapWithTestApp(CriticalAlertBanner(criticalCount: 0, onTap: () {})),
      );

      expect(find.text('critical alert'), findsNothing);
    });

    testWidgets('renders banner with correct count', (tester) async {
      var tapped = false;
      await tester.pumpWidget(
        wrapWithTestApp(
          Scaffold(
            body: CriticalAlertBanner(
              criticalCount: 2,
              onTap: () => tapped = true,
            ),
          ),
        ),
      );

      expect(find.textContaining('2 critical alerts'), findsOneWidget);
      await tester.tap(find.textContaining('2 critical alerts'));
      expect(tapped, isTrue);
    });

    testWidgets('uses singular form for 1 alert', (tester) async {
      await tester.pumpWidget(
        wrapWithTestApp(
          Scaffold(body: CriticalAlertBanner(criticalCount: 1, onTap: () {})),
        ),
      );

      expect(find.textContaining('1 critical alert'), findsOneWidget);
      // Should NOT contain "alerts" (plural)
      expect(find.textContaining('1 critical alerts'), findsNothing);
    });
  });
}
