-- Products catalog (global, shared by all households)
create table if not exists products (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  category     text not null,
  avg_price    numeric not null default 0,
  unit         text not null default 'un'
);

alter table products enable row level security;
create policy "read products" on products for select to authenticated using (true);

-- Add items column to purchase_records
alter table purchase_records add column if not exists items_json text;

-- Insert all products
insert into products (name, category, avg_price, unit) values
('Maca', 'Frutas', 0.89, 'kg'),
('Pera', 'Frutas', 0.99, 'kg'),
('Banana', 'Frutas', 1.29, 'kg'),
('Laranja', 'Frutas', 0.79, 'kg'),
('Limao', 'Frutas', 0.79, 'kg'),
('Morango', 'Frutas', 2.49, 'pack'),
('Uva', 'Frutas', 2.99, 'kg'),
('Melao', 'Frutas', 1.49, 'un'),
('Kiwi', 'Frutas', 1.99, 'kg'),
('Pessego', 'Frutas', 2.49, 'kg'),
('Manga', 'Frutas', 1.49, 'un'),
('Ameixa', 'Frutas', 2.49, 'kg'),
('Tomate', 'Legumes', 1.49, 'kg'),
('Cebola', 'Legumes', 0.89, 'kg'),
('Alho', 'Legumes', 1.99, 'pack'),
('Batata', 'Legumes', 0.79, 'kg'),
('Cenoura', 'Legumes', 0.99, 'kg'),
('Alface', 'Legumes', 0.89, 'un'),
('Pepino', 'Legumes', 0.79, 'un'),
('Courgette', 'Legumes', 1.29, 'kg'),
('Pimento', 'Legumes', 1.99, 'kg'),
('Broculos', 'Legumes', 1.49, 'un'),
('Couve', 'Legumes', 0.99, 'un'),
('Espinafre', 'Legumes', 1.29, 'pack'),
('Alho frances', 'Legumes', 1.29, 'kg'),
('Cogumelos', 'Legumes', 2.49, 'pack'),
('Beringela', 'Legumes', 1.49, 'kg'),
('Feijao verde', 'Legumes', 1.49, 'kg'),
('Ervilhas', 'Legumes', 1.29, 'pack'),
('Frango inteiro', 'Carnes', 4.99, 'kg'),
('Peito de frango', 'Carnes', 6.99, 'kg'),
('Carne picada', 'Carnes', 5.99, 'kg'),
('Costeletas de porco', 'Carnes', 4.99, 'kg'),
('Lombo de porco', 'Carnes', 5.99, 'kg'),
('Bife de vaca', 'Carnes', 9.99, 'kg'),
('Entrecosto', 'Carnes', 5.49, 'kg'),
('Chourico', 'Carnes', 3.49, 'un'),
('Linguica', 'Carnes', 2.99, 'un'),
('Fiambre', 'Carnes', 2.49, 'un'),
('Peru peito', 'Carnes', 7.99, 'kg'),
('Alheira', 'Carnes', 2.49, 'un'),
('Pescada', 'Peixe', 4.99, 'kg'),
('Bacalhau', 'Peixe', 12.99, 'kg'),
('Salmao', 'Peixe', 9.99, 'kg'),
('Atum em lata', 'Peixe', 1.49, 'un'),
('Sardinha em lata', 'Peixe', 0.99, 'un'),
('Camarao', 'Peixe', 9.99, 'kg'),
('Polvo', 'Peixe', 5.99, 'kg'),
('Pota', 'Peixe', 3.99, 'kg'),
('Dourada', 'Peixe', 7.99, 'kg'),
('Robalo', 'Peixe', 8.99, 'kg'),
('Leite', 'Laticinios', 0.79, 'L'),
('Iogurte natural', 'Laticinios', 0.49, 'un'),
('Iogurte pack 4', 'Laticinios', 1.29, 'pack'),
('Queijo flamengo', 'Laticinios', 2.99, 'un'),
('Manteiga', 'Laticinios', 1.99, 'un'),
('Natas', 'Laticinios', 0.99, 'un'),
('Mozzarella', 'Laticinios', 2.49, 'un'),
('Requeijao', 'Laticinios', 1.49, 'un'),
('Queijo parmesao', 'Laticinios', 4.99, 'un'),
('Pao de forma', 'Pao e Cereais', 1.29, 'un'),
('Pao de mistura', 'Pao e Cereais', 0.89, 'un'),
('Baguete', 'Pao e Cereais', 0.29, 'un'),
('Arroz', 'Pao e Cereais', 1.29, 'kg'),
('Massa esparguete', 'Pao e Cereais', 0.89, 'un'),
('Massa penne', 'Pao e Cereais', 0.99, 'un'),
('Farinha', 'Pao e Cereais', 0.89, 'kg'),
('Aveia', 'Pao e Cereais', 1.49, 'un'),
('Cereais pequeno-almoco', 'Pao e Cereais', 2.99, 'un'),
('Granola', 'Pao e Cereais', 3.49, 'un'),
('Ovos 12 un', 'Ovos', 2.49, 'pack'),
('Ovos 6 un', 'Ovos', 1.29, 'pack'),
('Tomate pelado lata', 'Conservas', 0.79, 'un'),
('Feijao vermelho lata', 'Conservas', 0.99, 'un'),
('Grao cozido lata', 'Conservas', 0.99, 'un'),
('Lentilhas cozidas lata', 'Conservas', 1.29, 'un'),
('Milho lata', 'Conservas', 0.79, 'un'),
('Azeite 750ml', 'Azeite e Condimentos', 4.99, 'un'),
('Oleo alimentar 1L', 'Azeite e Condimentos', 2.49, 'un'),
('Sal', 'Azeite e Condimentos', 0.49, 'kg'),
('Acucar', 'Azeite e Condimentos', 0.89, 'kg'),
('Molho de tomate', 'Azeite e Condimentos', 1.29, 'un'),
('Ketchup', 'Azeite e Condimentos', 1.49, 'un'),
('Maionese', 'Azeite e Condimentos', 1.99, 'un'),
('Mostarda', 'Azeite e Condimentos', 1.29, 'un'),
('Pimenta preta', 'Azeite e Condimentos', 1.49, 'un'),
('Colorau', 'Azeite e Condimentos', 0.99, 'un'),
('Vinagre', 'Azeite e Condimentos', 0.79, 'un'),
('Louro', 'Azeite e Condimentos', 0.89, 'un'),
('Oregaos', 'Azeite e Condimentos', 0.89, 'un'),
('Agua 6x1.5L', 'Bebidas', 1.99, 'pack'),
('Sumo laranja 1L', 'Bebidas', 1.29, 'un'),
('Refrigerante 1.5L', 'Bebidas', 1.79, 'un'),
('Cerveja pack 6', 'Bebidas', 3.99, 'pack'),
('Vinho tinto 750ml', 'Bebidas', 4.99, 'un'),
('Vinho branco 750ml', 'Bebidas', 4.99, 'un'),
('Cafe 250g', 'Bebidas', 2.99, 'un'),
('Cha 20 saquetas', 'Bebidas', 1.49, 'un'),
('Leite vegetal 1L', 'Bebidas', 1.99, 'un'),
('Pizza congelada', 'Congelados', 2.99, 'un'),
('Legumes congelados', 'Congelados', 1.49, 'pack'),
('Batatas fritas congeladas', 'Congelados', 2.49, 'pack'),
('Gelado', 'Congelados', 2.99, 'un'),
('Frango congelado', 'Congelados', 3.99, 'kg'),
('Bolachas Maria', 'Snacks', 0.89, 'un'),
('Bolachas manteiga', 'Snacks', 1.29, 'un'),
('Batatas fritas pack', 'Snacks', 1.49, 'un'),
('Chocolate tablete', 'Snacks', 1.49, 'un'),
('Barras de cereais', 'Snacks', 2.49, 'pack'),
('Frutos secos', 'Snacks', 3.49, 'pack'),
('Detergente louca', 'Limpeza', 1.99, 'un'),
('Detergente roupa', 'Limpeza', 6.99, 'un'),
('Amaciador', 'Limpeza', 3.99, 'un'),
('Limpa casas', 'Limpeza', 2.49, 'un'),
('Papel higienico 12un', 'Limpeza', 4.99, 'pack'),
('Toalhas de papel', 'Limpeza', 1.99, 'pack'),
('Sacos do lixo', 'Limpeza', 1.29, 'pack'),
('Esponjas', 'Limpeza', 1.49, 'pack'),
('Limpa vidros', 'Limpeza', 1.99, 'un'),
('Desinfetante', 'Limpeza', 2.49, 'un'),
('Pastilhas maquina louca', 'Limpeza', 5.99, 'pack'),
('Sabonete', 'Higiene', 0.99, 'un'),
('Champo', 'Higiene', 2.99, 'un'),
('Gel de banho', 'Higiene', 2.49, 'un'),
('Pasta de dentes', 'Higiene', 1.99, 'un'),
('Desodorizante', 'Higiene', 2.49, 'un'),
('Creme hidratante', 'Higiene', 3.99, 'un'),
('Laminas de barbear', 'Higiene', 3.99, 'pack'),
('Pensos', 'Higiene', 2.99, 'pack'),
('Cotonetes', 'Higiene', 1.29, 'pack');
